# Generated by Django 3.0 on 2021-04-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy', models.CharField(choices=[('sDisagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('sAgree', 'Strongly Agree')], max_length=200)),
                ('sad', models.CharField(choices=[('sDisagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('sAgree', 'Strongly Agree')], max_length=200)),
                ('tired', models.CharField(choices=[('sDisagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('sAgree', 'Strongly Agree')], max_length=200)),
                ('jittery', models.CharField(choices=[('sDisagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('sAgree', 'Strongly Agree')], max_length=200)),
                ('scale', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200)),
                ('feedback', models.CharField(default='', max_length=200)),
                ('user', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy', models.CharField(choices=[('sDisagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('sAgree', 'Strongly Agree')], max_length=200)),
                ('sad', models.CharField(choices=[('sDisagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('sAgree', 'Strongly Agree')], max_length=200)),
                ('tired', models.CharField(choices=[('sDisagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('sAgree', 'Strongly Agree')], max_length=200)),
                ('jittery', models.CharField(choices=[('sDisagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('sAgree', 'Strongly Agree')], max_length=200)),
                ('scale', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200)),
                ('interest', models.CharField(choices=[('listening', 'Music'), ('drawing', 'Art')], max_length=200)),
                ('user', models.CharField(default='', max_length=200)),
                ('chosen_system', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
