# Generated by Django 3.0 on 2021-03-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotionForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final',
            name='created',
        ),
        migrations.RemoveField(
            model_name='initial',
            name='created',
        ),
    ]
