# Generated by Django 3.0 on 2021-03-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionForm', '0002_auto_20210311_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initial',
            name='interest',
            field=models.CharField(choices=[('listening', 'Music'), ('drawing', 'Art')], max_length=200),
        ),
    ]
