# Generated by Django 3.0 on 2021-03-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionForm', '0003_auto_20210330_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='initial',
            name='chosen_system',
            field=models.CharField(default='', max_length=200),
        ),
    ]
