# Generated by Django 3.0 on 2021-04-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionForm', '0004_initial_chosen_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final',
            name='user',
        ),
        migrations.AddField(
            model_name='final',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='initial',
            name='user',
        ),
        migrations.AddField(
            model_name='initial',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
